### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [teto/home#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by teto** [comment]
Fixed with https://github.com/teto/home/commit/6d782251f76c06939e570f6bae4e0e217ce8c374

**Comment by karan** [comment]
Thanks a lot

**Comment by teto** [comment]
I wish you embedded how to proceed in the first message (from github interface "Add a file" allows to choose a licence). It is easy but when you don't know you may not want to do the effort.

**Comment by karan** [comment]
So true. I should've yes!
